### ISSUE TITLE
project fails to build

### ISSUE THREAD

**Issue by sloxy** [jhipster/jhipster-sample-app-react#11]
Following the instructions and running `./mvnw` results ultimately fails with errors:

```
jhipster-sample-app-react/src/test/java/io/github/jhipster/sample/service/mapper/LabelMapperTest.java:[13,23] io.github.jhipster.sample.service.mapper.LabelMapper is abstract; cannot be instantiated
```

same issue with OperationMapperTest, BankAccountMapperTest

Commenting out those classes and re-running `./mvnw` results in application running.

**Comment by pascalgrimaud** [comment]
Closing this ticket as it's a generated project
plz open a ticket with full details at https://github.com/jhipster/generator-jhipster
